# Generated by Django 4.2 on 2026-03-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_purchase_sale_stocktransaction_saleitem_purchaseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='received_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('credit', 'Credit')], max_length=20),
        ),
    ]
