# Generated by Django 5.2.9 on 2026-04-13 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_rename_phone_supplier_phone_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktransaction',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='reference_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='reference_type',
            field=models.CharField(blank=True, choices=[('sale', 'Sale Invoice'), ('return', 'Sales Return'), ('po', 'Purchase Order'), ('manual', 'Manual Entry'), ('project', 'Project Issue')], max_length=20, null=True),
        ),
    ]
