# Generated by Django 5.2.9 on 2026-04-13 16:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_alter_stocktransaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GRN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_no', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('grn_date', models.DateField(default=django.utils.timezone.now)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('delivery_note_no', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_no', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_no', models.CharField(blank=True, max_length=50, null=True)),
                ('received_by', models.CharField(blank=True, max_length=150, null=True)),
                ('inspected_by', models.CharField(blank=True, max_length=150, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=150, null=True)),
                ('quality_check_passed', models.BooleanField(default=False)),
                ('quality_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('received', 'Received'), ('inspected', 'Inspected'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grns', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='pos.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grns', to='pos.supplier')),
            ],
            options={
                'verbose_name': 'GRN',
                'verbose_name_plural': 'GRNs',
                'ordering': ['-grn_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GRNItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity_accepted', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity_rejected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quality_status', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged'), ('rejected', 'Rejected')], default='good', max_length=20)),
                ('quality_notes', models.TextField(blank=True, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.grn')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grn_items', to='pos.item')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grn_items', to='pos.purchaseorderitem')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('grn', 'purchase_order_item')},
            },
        ),
    ]
