# Generated by Django 5.2.9 on 2026-04-13 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_grn_grnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_items', to='pos.item'),
        ),
    ]
