# Generated by Django 4.2 on 2026-03-28 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0007_salesreturn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturn',
            name='item',
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='return_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='salesreturn',
            name='sale_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.saleitem'),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='return_type',
            field=models.CharField(choices=[('refund', 'Refund'), ('replace', 'Replace'), ('repair', 'Repair')], default='refund', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesreturn',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.sale'),
        ),
    ]
