# Generated by Django 5.2.9 on 2026-04-13 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_purchaseorderitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grnitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grn_items', to='pos.item'),
        ),
    ]
