# Generated by Django 4.2 on 2026-03-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_remove_salesreturn_item_salesreturn_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost_gl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='retail_gl',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
