# Generated by Django 5.2.9 on 2026-04-17 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_userlog_auditlog'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='pos_auditlog_timestamp_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='pos_auditlog_user_timestamp_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='pos_auditlog_model_timestamp_idx',
        ),
        migrations.RemoveIndex(
            model_name='userlog',
            name='pos_userlog_timestamp_idx',
        ),
        migrations.RemoveIndex(
            model_name='userlog',
            name='pos_userlog_user_timestamp_idx',
        ),
    ]
