# Generated by Django 5.2.9 on 2026-04-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_remove_auditlog_pos_auditlog_timestamp_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
    ]
