# Generated by Django 5.2.9 on 2026-04-27 07:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_alter_purchaseorder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexpense',
            name='original_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_adjustments', to='pos.projectexpense'),
        ),
        migrations.AddField(
            model_name='projectincome',
            name='original_income',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_adjustments', to='pos.projectincome'),
        ),
        migrations.CreateModel(
            name='ProjectTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_no', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('transfer_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income')], max_length=20)),
                ('transfer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('transfer_date', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_project_transfers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_transfers', to=settings.AUTH_USER_MODEL)),
                ('from_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='pos.project')),
                ('original_project_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_transfers', to='pos.projectexpense')),
                ('original_project_income', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_transfers', to='pos.projectincome')),
                ('to_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='pos.project')),
            ],
            options={
                'ordering': ['-transfer_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_expense_entries', to='pos.projecttransfer'),
        ),
        migrations.AddField(
            model_name='projectincome',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_income_entries', to='pos.projecttransfer'),
        ),
    ]
