# Generated by Django 4.2 on 2026-04-01 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_projectexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexpense',
            name='expense_type',
            field=models.CharField(choices=[('inventory', 'Inventory Item'), ('direct', 'Direct Item'), ('service', 'Service')], default='direct', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='gl_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.glmaster'),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.project'),
        ),
        migrations.AlterField(
            model_name='projectexpense',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
    ]
