# Generated by Django 5.2.9 on 2026-06-07 14:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_quotation_quotationitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('total_budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='pos.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectBudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='pos.projectbudget')),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='pos.glmaster')),
            ],
            options={
                'ordering': ['gl_account__gl_code'],
                'unique_together': {('budget', 'gl_account')},
            },
        ),
        migrations.CreateModel(
            name='ProjectCostActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('project_expense', 'Project Expense'), ('petty_cash', 'Petty Cash Expense'), ('grn_issue', 'GRN Issue'), ('inventory_issue', 'Inventory Issue'), ('supplier_settlement', 'Supplier Settlement')], max_length=30)),
                ('source_id', models.CharField(max_length=100)),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gl_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_actuals', to='pos.glmaster')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_actuals', to='pos.project')),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
                'indexes': [models.Index(fields=['project', 'gl_account'], name='pos_project_project_65820a_idx'), models.Index(fields=['project', 'source_type'], name='pos_project_project_f20e6f_idx')],
            },
        ),
    ]
