# Generated by Django 4.2 on 2026-04-01 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0015_projectincome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectincome',
            options={'ordering': ['-income_date', '-id']},
        ),
        migrations.RemoveField(
            model_name='projectincome',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='projectincome',
            name='received_from',
        ),
        migrations.RemoveField(
            model_name='projectincome',
            name='reference_no',
        ),
        migrations.RemoveField(
            model_name='projectincome',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='projectincome',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='projectincome',
            name='gl_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.glmaster'),
        ),
        migrations.AlterField(
            model_name='item',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='projectincome',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='projectincome',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectincome',
            name='income_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('opening', 'Opening Stock'), ('purchase', 'Purchase'), ('sale', 'Sale'), ('adjust_plus', 'Adjustment +'), ('adjust_minus', 'Adjustment -'), ('project_issue', 'Project Issue'), ('return_in', 'Return In')], max_length=20),
        ),
    ]
