# Generated by Django 5.2.9 on 2026-06-10 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_glcreationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('business_registration', 'Business Registration'), ('trade_license', 'Trade License'), ('vehicle_revenue_license', 'Vehicle Revenue License'), ('vehicle_insurance', 'Vehicle Insurance'), ('environmental_permit', 'Environmental Permit'), ('contractor_registration', 'Contractor Registration'), ('tax_registration', 'Tax Registration'), ('epf_etf_registrations', 'EPF / ETF Registrations'), ('company_certifications', 'Company Certifications'), ('other_licenses', 'Other Licenses')], max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('current_renewal_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('next_renewal_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('closed', 'Closed')], default='active', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='license_renewals', to='pos.employee')),
            ],
            options={
                'ordering': ['next_renewal_date', 'expire_date', 'description'],
            },
        ),
    ]
