# Generated by Django 4.2 on 2026-04-02 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0016_alter_projectincome_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpettycash',
            name='issued_to',
        ),
        migrations.RemoveField(
            model_name='projectpettycash',
            name='project',
        ),
        migrations.AddField(
            model_name='projectpettycash',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_received', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectpettycashexpense',
            name='bill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectpettycashexpense',
            name='bill_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectpettycashexpense',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_expenses', to='pos.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectpettycash',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
