# Generated by Django 5.2.9 on 2026-04-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_remove_projectpettycash_issued_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
