# Generated by Django 5.2.9 on 2026-07-02 15:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_payrollentry_payrollallocation_payrollglentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='employee',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('permanent', 'Permanent'), ('executive', 'Executive'), ('contract', 'Contract'), ('daily_labour', 'Daily Labour')], default='permanent', max_length=30),
        ),
        migrations.AddField(
            model_name='employee',
            name='epf_etf_applicable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='nic',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='LabourAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('work_type', models.CharField(blank=True, max_length=100, null=True)),
                ('working_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('ot_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('attendance_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('leave', 'Leave'), ('holiday', 'Holiday'), ('late', 'Late')], default='present', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_allocations', to='pos.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_allocations', to='pos.project')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_labour_allocations', to='pos.employee')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
