# Generated by Django 5.2.9 on 2026-04-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_sale_customer_name_sale_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexpense',
            name='expense_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projectpettycashexpense',
            name='expense_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
