# Generated by Django 5.2.9 on 2026-07-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_payrollallowance_payrolldeduction_salaryadvance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollentry',
            name='payslip_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
