# Generated by Django 5.2.9 on 2026-04-03 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_employee_projectpettycash_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('BL', 'Building'), ('SW', 'Swimming Pool'), ('RS', 'Retail Shop')], max_length=10),
        ),
    ]
