# Generated by Django 5.2.9 on 2026-07-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0021_payrollentry_payslip_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_based',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('daily', 'Daily'), ('contract', 'Contract')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='labourallocation',
            name='daily_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='labourallocation',
            name='ot_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='labourallocation',
            name='total_labour_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
