# Generated by Django 5.2.9 on 2026-07-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_employee_contract_based_employee_joining_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollentry',
            name='salary_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectinvoice',
            name='invoice_type',
            field=models.CharField(choices=[('advance', 'Advance'), ('progress', 'Progress'), ('final', 'Final'), ('payslip', 'Payslip'), ('other', 'Other')], default='advance', max_length=20),
        ),
    ]
