# Generated by Django 5.2.9 on 2026-04-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_projectinvoice_projectinvoicepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvoicepayment',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
