# Generated by Django 5.2.9 on 2026-07-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0024_glcreationlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesreturn',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled')], default='approved', max_length=20),
        ),
    ]
