# Generated by Django 5.2.9 on 2026-07-16 14:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_salesreturn_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollentry',
            name='epf_expense_gl_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_epf_expense_entries', to='pos.glmaster'),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='epf_payable_gl_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_epf_payable_entries', to='pos.glmaster'),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='etf_expense_gl_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_etf_expense_entries', to='pos.glmaster'),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='etf_payable_gl_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_etf_payable_entries', to='pos.glmaster'),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='deducted_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salaryadvance',
            name='deduction_month',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SafetyItemIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('safety_item', models.CharField(max_length=255)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=12)),
                ('item_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('deduction_month', models.DateField(blank=True, null=True)),
                ('deduct_from_salary', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('deducted', 'Deducted'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_item_issues', to='pos.employee')),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('half_day', 'Half Day'), ('leave', 'Leave'), ('holiday', 'Holiday'), ('late', 'Late')], default='present', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='pos.employee')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='pos.project')),
            ],
            options={
                'ordering': ['-date', 'employee__full_name'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
