# Generated by Django 5.2.9 on 2026-04-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0025_projectinvoiceitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinvoicepayment',
            name='inactive_at',
        ),
        migrations.RemoveField(
            model_name='projectinvoicepayment',
            name='inactive_by',
        ),
        migrations.RemoveField(
            model_name='projectinvoicepayment',
            name='inactive_reason',
        ),
        migrations.RemoveField(
            model_name='projectinvoicepayment',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='projectinvoicepayment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='projectinvoicepayment',
            name='card_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projectinvoicepayment',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projectinvoicepayment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('cheque', 'Cheque')], default='cash', max_length=20),
        ),
    ]
