# Generated by Django 5.2.9 on 2026-07-17 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0026_payrollentry_epf_expense_gl_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='default_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_employees', to='pos.project'),
        ),
        migrations.AddField(
            model_name='employee',
            name='default_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_supervised_employees', to='pos.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='ot_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='OT rate per hour. If blank/0, derived from daily/basic rate.', max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='holiday_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='leave_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='no_pay_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='ot_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], default='bank', max_length=10),
        ),
        migrations.AddField(
            model_name='payrollentry',
            name='present_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='project',
            name='default_cost_gl_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_using_as_cost_gl', to='pos.glmaster'),
        ),
        migrations.AddField(
            model_name='project',
            name='default_labour_gl_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_using_as_labour_gl', to='pos.glmaster'),
        ),
        migrations.AddField(
            model_name='project',
            name='default_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_projects', to='pos.employee'),
        ),
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_bank_gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pos.glmaster')),
                ('default_epf_expense_gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pos.glmaster')),
                ('default_epf_payable_gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pos.glmaster')),
                ('default_etf_expense_gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pos.glmaster')),
                ('default_etf_payable_gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pos.glmaster')),
                ('default_salary_payable_gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='pos.glmaster')),
            ],
            options={
                'verbose_name': 'Payroll Settings',
                'verbose_name_plural': 'Payroll Settings',
            },
        ),
    ]
