# Generated by Django 5.2.9 on 2026-04-04 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0027_projectinvoicepayment_inactive_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinvoice',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='projectinvoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_invoices', to=settings.AUTH_USER_MODEL),
        ),
    ]
