# Generated by Django 5.2.9 on 2026-08-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0028_backupsettings_backuprecord_restorelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuprecord',
            name='google_drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='backuprecord',
            name='google_drive_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='backupsettings',
            name='storage_location',
            field=models.CharField(choices=[('local', 'Local Server'), ('google_drive', 'Google Drive'), ('other', 'Other Cloud Storage (Coming soon)')], default='local', max_length=20),
        ),
    ]
