# Generated by Django 5.2.9 on 2026-04-05 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0028_remove_projectinvoice_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectexpense',
            name='inactive_at',
        ),
        migrations.RemoveField(
            model_name='projectexpense',
            name='inactive_by',
        ),
        migrations.RemoveField(
            model_name='projectexpense',
            name='inactive_reason',
        ),
        migrations.RemoveField(
            model_name='projectexpense',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='projectexpense',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='source_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_expense_rows', to='pos.sale'),
        ),
        migrations.AddField(
            model_name='sale',
            name='approval_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='approval_status',
            field=models.CharField(choices=[('na', 'Not Applicable'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='na', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='is_posted_to_project_expense',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales', to='pos.project'),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(choices=[('retail', 'Retail Sale'), ('project_issue', 'Project Issue')], default='retail', max_length=20),
        ),
    ]
