# Generated by Django 5.2.9 on 2026-09-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0029_backuprecord_google_drive_file_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupExecutionLock',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Backup Execution Lock',
                'verbose_name_plural': 'Backup Execution Lock',
            },
        ),
    ]
