# Generated by Django 5.2.9 on 2026-04-05 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0029_remove_projectexpense_inactive_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectexpense',
            name='inactive_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='inactive_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inactive_project_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='inactive_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectexpense',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
