# Generated by Django 5.2.9 on 2026-04-06 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0031_salerecovery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpettycashexpense',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='projectpettycashexpense',
            name='approval_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectpettycashexpense',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='projectpettycashexpense',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectpettycashexpense',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_petty_cash_expenses', to=settings.AUTH_USER_MODEL),
        ),
    ]
