# Generated by Django 6.1 on 2026-09-16 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0032_banktransaction_contra_gl_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="banktransaction",
            name="source_sale",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bank_transaction",
                to="pos.sale",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="barcode",
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="bank_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pos_sales",
                to="pos.bankaccount",
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="bank_transfer_reference",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="bank_transfer_remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("credit", "Credit"),
                    ("bank_transfer", "Bank Transfer"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
    ]
