# Generated by Django 5.2.9 on 2026-04-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0033_alter_employee_options_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='allow_discount',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='max_discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
