# Generated by Django 5.2.9 on 2026-09-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0035_cashadjustment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("credit", "Credit"),
                    ("bank_transfer", "Bank Transfer"),
                    ("cheque", "Cheque"),
                ],
                default="cash",
                max_length=20,
            ),
        ),
    ]
