# Generated by Django 5.2.9 on 2026-10-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pos", "0040_maintenance_cost_allocation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("na", "Not Applicable"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("void", "Void / Incomplete Sale"),
                ],
                default="na",
                max_length=20,
            ),
        ),
    ]
