"""
Month-End Maintenance Cost Allocation.

A Maintenance Main Project accumulates cost during a month. At month end the
whole balance must be allocated to eligible operational projects so that the
Maintenance Main Project closes at exactly Rs. 0.00. Posting uses the same
reversal + repost pattern as Project Transfer, but is a separate process with
its own audit records (MaintenanceAllocation / MaintenanceAllocationLine).
"""
import calendar
from datetime import date
from decimal import Decimal, InvalidOperation, ROUND_HALF_UP
from functools import wraps

from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.exceptions import PermissionDenied
from django.db import transaction
from django.db.models import Sum
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.views.decorators.http import require_POST

from .models import (
    GLMaster,
    MaintenanceAllocation,
    MaintenanceAllocationLine,
    Project,
    ProjectExpense,
    ProjectPettyCashExpense,
)
from .views import (
    _is_transfer_eligible_project,
    _limit_text,
    _transfer_eligible_projects,
    can_use_project,
    generate_project_expense_no,
    is_owner,
)

ZERO = Decimal("0.00")
CENT = Decimal("0.01")
EDITABLE_STATUSES = ("draft", "rejected")


class AllocationError(Exception):
    pass


def q2(value):
    return Decimal(value).quantize(CENT, rounding=ROUND_HALF_UP)


def owner_required(view):
    """Server-side Owner/Superuser check; direct URL calls by others get 403."""
    @wraps(view)
    @login_required
    def wrapper(request, *args, **kwargs):
        if not is_owner(request.user):
            raise PermissionDenied("Only the Owner/Super User can perform this action.")
        return view(request, *args, **kwargs)
    return wrapper


# ---------------------------------------------------------------------------
# Calculations
# ---------------------------------------------------------------------------
def parse_month(value):
    """'YYYY-MM' -> first day of that month, or None."""
    try:
        year, month = str(value).split("-")[:2]
        return date(int(year), int(month), 1)
    except (ValueError, TypeError):
        return None


def month_end(month):
    return date(month.year, month.month, calendar.monthrange(month.year, month.month)[1])


def _sum(qs):
    return qs.aggregate(total=Sum("amount"))["total"] or ZERO


def available_cost(project, month):
    """
    Net cost of the project in the month, using the same components as
    compute_project_profit_rows (direct expense + approved petty cash +
    transfer reversals - inventory returns), excluding rows generated by a
    maintenance allocation so the figure does not change after posting.
    ProjectCostActual is a derived cache of these same sources and is not used.
    """
    first, last = month, month_end(month)
    expenses = ProjectExpense.objects.filter(
        project=project, is_active=True, expense_date__range=(first, last),
        maintenance_allocation__isnull=True,
    )
    direct = _sum(expenses.filter(amount__gt=0))
    returns = abs(_sum(expenses.filter(amount__lt=0, expense_type="inventory", transfer__isnull=True)))
    transfer_reversals = _sum(expenses.filter(amount__lt=0, transfer__isnull=False))
    petty = _sum(ProjectPettyCashExpense.objects.filter(
        project=project, is_active=True, approval_status="approved",
        expense_date__range=(first, last),
    ))
    return q2(direct + petty + transfer_reversals - returns)


def closing_balance(project, month):
    """Month cost of the project after any posted (and not reversed) allocations."""
    allocation_rows = _sum(ProjectExpense.objects.filter(
        project=project, is_active=True, maintenance_allocation__isnull=False,
        expense_date__range=(month, month_end(month)),
    ))
    return q2(available_cost(project, month) + allocation_rows)


def allocated_total(allocation):
    return q2(allocation.lines.aggregate(total=Sum("amount"))["total"] or ZERO)


def check_zero_balance(available, allocated):
    remaining = q2(available) - q2(allocated)
    if remaining > ZERO:
        raise AllocationError(
            f"Cannot finalize. Maintenance Main Project has an unallocated balance of Rs. {remaining:,.2f}."
        )
    if remaining < ZERO:
        raise AllocationError(
            f"Cannot finalize. Allocation exceeds the available Maintenance Main Project cost by Rs. {abs(remaining):,.2f}."
        )


def ensure_month_not_posted(source_project, month, exclude_pk=None):
    qs = MaintenanceAllocation.objects.filter(source_project=source_project, month=month, status="posted")
    if exclude_pk:
        qs = qs.exclude(pk=exclude_pk)
    existing = qs.first()
    if existing:
        raise AllocationError(
            f"{existing.reference} is already posted for {month:%b %Y}. "
            "Reverse it before creating another allocation for this month."
        )


def _validate_destination(allocation, project):
    if project.id == allocation.source_project_id:
        raise AllocationError("The Maintenance Main Project cannot be a destination project.")
    if not _is_transfer_eligible_project(project):
        raise AllocationError(f"Project {project.project_id} is closed, cancelled or inactive.")


def build_lines(method, available, source_project, rows):
    """
    rows: list of dicts with project_id, value, gl_id, remarks. Returns validated
    line dicts. Amounts are Decimal, rounded to 2 places; for percentage
    allocations that total 100% the last line absorbs the rounding remainder.
    """
    rows = [r for r in rows if r["project_id"] or r["value"]]
    if not rows:
        raise AllocationError("Add at least one destination project.")

    lines, seen = [], set()
    for r in rows:
        if not r["project_id"]:
            raise AllocationError("Select a project for every allocation row.")
        try:
            project = Project.objects.get(id=int(r["project_id"]))
        except (ValueError, Project.DoesNotExist):
            raise AllocationError("Invalid destination project.")
        if project.id in seen:
            raise AllocationError(f"Duplicate destination project {project.project_id}.")
        seen.add(project.id)
        if project.id == source_project.id:
            raise AllocationError("The Maintenance Main Project cannot be a destination project.")
        if not _is_transfer_eligible_project(project):
            raise AllocationError(f"Project {project.project_id} is closed, cancelled or inactive.")
        try:
            value = Decimal(str(r["value"]).strip())
        except (InvalidOperation, ValueError):
            raise AllocationError(f"Invalid value for project {project.project_id}.")
        if value <= 0:
            raise AllocationError(f"Value for project {project.project_id} must be greater than zero.")
        gl = GLMaster.objects.filter(id=r["gl_id"]).first() if r["gl_id"] else None
        lines.append({"project": project, "value": value, "gl": gl, "remarks": (r["remarks"] or "")[:255]})

    available = q2(available)
    if method == "percent":
        total_pct = sum((l["value"] for l in lines), Decimal("0"))
        if total_pct > Decimal("100"):
            raise AllocationError("Total allocation percentage cannot exceed 100%.")
        for l in lines:
            l["percent"] = l["value"]
            l["amount"] = q2(available * l["value"] / Decimal("100"))
        if total_pct == Decimal("100"):
            lines[-1]["amount"] = available - sum((l["amount"] for l in lines[:-1]), ZERO)
    else:
        for l in lines:
            l["amount"] = q2(l["value"])
            l["percent"] = (
                (l["amount"] * Decimal("100") / available).quantize(Decimal("0.0001"), rounding=ROUND_HALF_UP)
                if available > 0 else Decimal("0")
            )

    total = sum((l["amount"] for l in lines), ZERO)
    if total > available:
        raise AllocationError(
            f"Allocation exceeds the available Maintenance Main Project cost by Rs. {total - available:,.2f}."
        )
    if any(l["amount"] <= 0 for l in lines):
        raise AllocationError("Every allocation amount must be greater than zero.")
    return lines


# ---------------------------------------------------------------------------
# Workflow operations (each is atomic)
# ---------------------------------------------------------------------------
def _locked(pk):
    return MaintenanceAllocation.objects.select_for_update().select_related("source_project").get(pk=pk)


@transaction.atomic
def submit_allocation(user, pk):
    alloc = _locked(pk)
    if alloc.status not in EDITABLE_STATUSES:
        raise AllocationError("Only draft or rejected allocations can be submitted.")
    if not alloc.lines.exists():
        raise AllocationError("Add at least one allocation line before submitting.")
    ensure_month_not_posted(alloc.source_project, alloc.month, alloc.pk)
    alloc.status = "pending"
    alloc.submitted_by, alloc.submitted_at = user, timezone.now()
    alloc.save()


def _final_checks(alloc):
    """Shared by approve and post: recompute cost live and require an exact zero balance."""
    lines = list(alloc.lines.select_related("project"))
    if not lines:
        raise AllocationError("The allocation has no lines.")
    for line in lines:
        _validate_destination(alloc, line.project)
        if line.amount <= 0:
            raise AllocationError("Every allocation amount must be greater than zero.")
    available = available_cost(alloc.source_project, alloc.month)
    if available <= 0:
        raise AllocationError("The Maintenance Main Project has no cost to allocate for this month.")
    check_zero_balance(available, allocated_total(alloc))
    return lines, available


@transaction.atomic
def approve_allocation(user, pk):
    alloc = _locked(pk)
    if alloc.status != "pending":
        raise AllocationError("Only allocations pending approval can be approved.")
    ensure_month_not_posted(alloc.source_project, alloc.month, alloc.pk)
    _, available = _final_checks(alloc)
    alloc.available_amount = available
    alloc.status = "approved"
    alloc.approved_by, alloc.approved_at = user, timezone.now()
    alloc.save()


@transaction.atomic
def reject_allocation(user, pk, reason):
    alloc = _locked(pk)
    if alloc.status not in ("pending", "approved"):
        raise AllocationError("Only pending or approved allocations can be rejected.")
    alloc.status = "rejected"
    alloc.rejected_by, alloc.rejected_at = user, timezone.now()
    alloc.rejection_reason = reason
    alloc.save()


@transaction.atomic
def post_allocation(user, pk):
    alloc = _locked(pk)
    if alloc.status == "posted":
        raise AllocationError("This allocation is already posted.")
    if alloc.status != "approved":
        raise AllocationError("Only approved allocations can be posted.")
    if MaintenanceAllocation.objects.filter(
        source_project=alloc.source_project, month=alloc.month, status="posted"
    ).exclude(pk=alloc.pk).exists():
        raise AllocationError("This project/month already has a posted allocation. Reverse it first.")

    lines, available = _final_checks(alloc)
    source = alloc.source_project
    posting_date = month_end(alloc.month)
    label = f"{alloc.month:%b %Y}"

    for line in lines:
        for project, sign, prefix in ((source, -1, "Reversal"), (line.project, 1, "Repost")):
            ProjectExpense.objects.create(
                expense_no=generate_project_expense_no(),
                project=project,
                expense_type="direct",
                expense_date=posting_date,
                description=_limit_text(
                    f"{prefix} - maintenance cost allocation {alloc.reference} ({label}) "
                    f"{source.project_id} -> {line.project.project_id}"
                ),
                qty=0,
                unit_price=0,
                amount=sign * line.amount,
                gl_account=line.gl_account,
                maintenance_allocation=alloc,
                maintenance_allocation_line=line,
                created_by=user,
            )

    alloc.available_amount = available
    alloc.status = "posted"
    alloc.posted_by, alloc.posted_at = user, timezone.now()
    alloc.save()


@transaction.atomic
def reverse_allocation(user, pk, reason):
    alloc = _locked(pk)
    if alloc.status != "posted":
        raise AllocationError("Only posted allocations can be reversed.")
    if not reason:
        raise AllocationError("A reason is required to reverse a posted allocation.")

    originals = list(ProjectExpense.objects.select_for_update().filter(
        maintenance_allocation=alloc, original_expense__isnull=True,
    ))
    if not originals:
        raise AllocationError("No posted rows were found for this allocation.")
    for row in originals:
        ProjectExpense.objects.create(
            expense_no=generate_project_expense_no(),
            project=row.project,
            expense_type=row.expense_type,
            expense_date=row.expense_date,
            description=_limit_text(f"Reversal of {row.expense_no} - allocation {alloc.reference}: {reason}"),
            qty=0,
            unit_price=0,
            amount=-row.amount,
            gl_account=row.gl_account,
            maintenance_allocation=alloc,
            maintenance_allocation_line=row.maintenance_allocation_line,
            original_expense=row,
            created_by=user,
        )
    alloc.status = "reversed"
    alloc.reversed_by, alloc.reversed_at = user, timezone.now()
    alloc.reversal_reason = reason
    alloc.save()


# ---------------------------------------------------------------------------
# Views
# ---------------------------------------------------------------------------
def _read_rows(post):
    projects = post.getlist("line_project")
    values = post.getlist("line_value")
    gls = post.getlist("line_gl")
    remarks = post.getlist("line_remarks")
    rows = []
    for i, pid in enumerate(projects):
        rows.append({
            "project_id": pid,
            "value": values[i] if i < len(values) else "",
            "gl_id": gls[i] if i < len(gls) else "",
            "remarks": remarks[i] if i < len(remarks) else "",
        })
    return rows


def _form_context(allocation, post=None, rows=None):
    return {
        "allocation": allocation,
        "projects": _transfer_eligible_projects(Project.objects.all()).order_by("project_id"),
        "gl_accounts": GLMaster.objects.filter(is_active=True),
        "method_choices": MaintenanceAllocation.METHOD_CHOICES,
        "rows": rows if rows is not None else [
            {"project_id": str(l.project_id), "value": l.percent if allocation.method == "percent" else l.amount,
             "gl_id": str(l.gl_account_id or ""), "remarks": l.remarks or ""}
            for l in allocation.lines.all()
        ] if allocation and allocation.pk else [],
        "post": post or {},
    }


def _save_draft(request, allocation):
    post = request.POST
    month = parse_month(post.get("month"))
    if not month:
        raise AllocationError("Select a valid accounting month.")
    source = Project.objects.filter(id=post.get("source_project") or 0).first()
    if not source:
        raise AllocationError("Select the Maintenance Main Project.")
    if not _is_transfer_eligible_project(source):
        raise AllocationError("The Maintenance Main Project is closed or inactive.")
    method = post.get("method") if post.get("method") in ("amount", "percent") else "amount"
    ensure_month_not_posted(source, month, allocation.pk if allocation else None)
    available = available_cost(source, month)
    lines = build_lines(method, available, source, _read_rows(post))

    with transaction.atomic():
        if allocation is None:
            allocation = MaintenanceAllocation(created_by=request.user)
        elif allocation.status not in EDITABLE_STATUSES:
            raise AllocationError("Posted or submitted allocations cannot be edited.")
        allocation.month, allocation.source_project, allocation.method = month, source, method
        allocation.available_amount = available
        allocation.remarks = (post.get("remarks") or "").strip()
        if allocation.status == "rejected":
            allocation.status = "draft"
        allocation.save()
        allocation.lines.all().delete()
        for l in lines:
            MaintenanceAllocationLine.objects.create(
                allocation=allocation, project=l["project"], percent=l["percent"],
                amount=l["amount"], gl_account=l["gl"], remarks=l["remarks"],
            )
    return allocation


def _form_view(request, allocation=None):
    if allocation is not None and allocation.status not in EDITABLE_STATUSES:
        messages.error(request, "Only draft or rejected allocations can be edited.")
        return redirect("maintenance_allocation_detail", pk=allocation.pk)
    if request.method == "POST":
        try:
            allocation = _save_draft(request, allocation)
        except AllocationError as exc:
            messages.error(request, str(exc))
            return render(request, "pos/maintenance_allocation_form.html",
                          _form_context(allocation, post=request.POST, rows=_read_rows(request.POST)))
        if request.POST.get("action") == "submit":
            try:
                submit_allocation(request.user, allocation.pk)
                messages.success(request, f"{allocation.reference} submitted for approval.")
            except AllocationError as exc:
                messages.error(request, str(exc))
        else:
            messages.success(request, f"{allocation.reference} saved as draft.")
        return redirect("maintenance_allocation_detail", pk=allocation.pk)
    return render(request, "pos/maintenance_allocation_form.html", _form_context(allocation))


@user_passes_test(can_use_project)
def maintenance_allocation_list(request):
    qs = MaintenanceAllocation.objects.select_related("source_project", "created_by")
    status = request.GET.get("status")
    if status:
        qs = qs.filter(status=status)
    return render(request, "pos/maintenance_allocation_list.html", {
        "allocations": qs,
        "status_choices": MaintenanceAllocation.STATUS_CHOICES,
        "selected_status": status or "",
        "is_owner": is_owner(request.user),
    })


@user_passes_test(can_use_project)
def maintenance_allocation_create(request):
    return _form_view(request)


@user_passes_test(can_use_project)
def maintenance_allocation_edit(request, pk):
    return _form_view(request, get_object_or_404(MaintenanceAllocation, pk=pk))


@user_passes_test(can_use_project)
def maintenance_allocation_available(request):
    """JSON helper for the form: live available cost for a project and month."""
    project = Project.objects.filter(id=request.GET.get("project") or 0).first()
    month = parse_month(request.GET.get("month"))
    if not project or not month:
        return JsonResponse({"available": None})
    return JsonResponse({"available": str(available_cost(project, month))})


@user_passes_test(can_use_project)
def maintenance_allocation_detail(request, pk):
    alloc = get_object_or_404(
        MaintenanceAllocation.objects.select_related(
            "source_project", "created_by", "submitted_by", "approved_by",
            "rejected_by", "posted_by", "reversed_by",
        ), pk=pk,
    )
    live = alloc.status not in ("posted", "reversed")
    available = available_cost(alloc.source_project, alloc.month) if live else alloc.available_amount
    allocated = allocated_total(alloc)
    remaining = q2(available) - allocated
    owner = is_owner(request.user)
    return render(request, "pos/maintenance_allocation_detail.html", {
        "allocation": alloc,
        "lines": alloc.lines.select_related("project", "gl_account"),
        "entries": alloc.project_expense_entries.select_related("project", "gl_account").order_by("id"),
        "available": q2(available),
        "allocated": allocated,
        "remaining": remaining,
        "balanced": remaining == ZERO,
        "month_closing": closing_balance(alloc.source_project, alloc.month),
        "is_owner": owner,
        "can_edit": alloc.status in EDITABLE_STATUSES,
        "can_submit": alloc.status in EDITABLE_STATUSES and alloc.lines.exists(),
        "can_approve": owner and alloc.status == "pending",
        "can_reject": owner and alloc.status in ("pending", "approved"),
        "can_post": owner and alloc.status == "approved",
        "can_reverse": owner and alloc.status == "posted",
    })


def _run_action(request, pk, func, success, *extra):
    try:
        func(request.user, pk, *extra)
        messages.success(request, success)
    except AllocationError as exc:
        messages.error(request, str(exc))
    return redirect("maintenance_allocation_detail", pk=pk)


@require_POST
@user_passes_test(can_use_project)
def maintenance_allocation_submit(request, pk):
    return _run_action(request, pk, submit_allocation, "Submitted for approval.")


@owner_required
@require_POST
def maintenance_allocation_approve(request, pk):
    return _run_action(request, pk, approve_allocation, "Allocation approved.")


@owner_required
@require_POST
def maintenance_allocation_reject(request, pk):
    return _run_action(request, pk, reject_allocation, "Allocation rejected.",
                       (request.POST.get("reason") or "").strip())


@owner_required
@require_POST
def maintenance_allocation_post(request, pk):
    return _run_action(request, pk, post_allocation, "Allocation posted.")


@owner_required
@require_POST
def maintenance_allocation_reverse(request, pk):
    return _run_action(request, pk, reverse_allocation, "Allocation reversed.",
                       (request.POST.get("reason") or "").strip())


@user_passes_test(can_use_project)
def maintenance_allocation_report(request):
    lines = MaintenanceAllocationLine.objects.select_related(
        "allocation", "allocation__source_project", "allocation__created_by",
        "allocation__approved_by", "project",
    ).order_by("-allocation__month", "allocation__reference", "id")

    month = request.GET.get("month") or ""
    source = request.GET.get("source_project") or ""
    dest = request.GET.get("destination_project") or ""
    status = request.GET.get("status") or ""
    reference = (request.GET.get("reference") or "").strip()
    if month and parse_month(month):
        lines = lines.filter(allocation__month=parse_month(month))
    if source:
        lines = lines.filter(allocation__source_project_id=source)
    if dest:
        lines = lines.filter(project_id=dest)
    if status:
        lines = lines.filter(allocation__status=status)
    if reference:
        lines = lines.filter(allocation__reference__icontains=reference)

    lines = list(lines)
    posted_lines = [l for l in lines if l.allocation.status == "posted"]
    posted_allocs = {l.allocation_id: l.allocation for l in posted_lines}
    total_available = sum((a.available_amount for a in posted_allocs.values()), ZERO)
    total_allocated = sum((l.amount for l in posted_lines), ZERO)
    # Live balance of each posted month: non-zero means cost was entered for that
    # month after posting (late entry). It is reported, never silently re-allocated.
    late_variances = []
    live_closing = ZERO
    for a in posted_allocs.values():
        bal = closing_balance(a.source_project, a.month)
        live_closing += bal
        if bal != ZERO:
            late_variances.append({"allocation": a, "balance": bal})

    return render(request, "pos/maintenance_allocation_report.html", {
        "lines": lines,
        "total_available": total_available,
        "total_allocated": total_allocated,
        "closing_balance": live_closing,
        "late_variances": late_variances,
        "projects": Project.objects.order_by("project_id"),
        "status_choices": MaintenanceAllocation.STATUS_CHOICES,
        "f": {"month": month, "source_project": source, "destination_project": dest,
              "status": status, "reference": reference},
    })
